### ISSUE TITLE
Scale down images so they load faster

### ISSUE THREAD

**Issue by phase** [TheNexusMC-LLC/Issues#1]
When viewing https://thenexusmc.com/, my terrible internet and I notice that some of the images take a while to load in. This is especially bad with the _Games Just Finished_ images.

Compare these two images. The first is it loaded in fully.
![what it should be](http://i.imgur.com/kSHfiWf.png)
This one hasn't been loaded in, and will take another 20-30 seconds to do so.
![what I see](http://i.imgur.com/FkrrQB6.png)

The culprit seems to be your giant pictures. Scaling down the resolution on 
![big pic](https://s3.amazonaws.com/f.cl.ly/items/040T1s0A0m0e3e032v2i/Screen%20Shot%202015-02-14%20at%203.42.22%20PM.png)
would help your storage and everyone who would like to load your page.

Edit: It's worse on the games page, and probably lots of other places.
![games page](http://i.imgur.com/PnQKoxo.png)

**Comment by Deamon5550** [comment]
Alright I've shrunk the ones on the /games and /games/sg pages, the ones on the recently played games tiles on the home page and /players will soon update as soon as I update the database in a couple of hours.

Let me know if there are any other pages that you notice have outrageously scaled images.

**Comment by phase** [comment]
This happened as soon as I went on the home page. It looks like a CSS error or something. The image loaded fine when I [opened it in a new tab](https://s3.amazonaws.com/f.cl.ly/items/3u3r1H2e2H0d1s3t2Y0A/HdqUQVg.jpg), but my internet is bad right now (hotspot in an airport).

![long boxes](http://i.imgur.com/BmOn8ba.png)

The logo on the home page and the image behind it took a while to load in, but it might be my internet again.

**Comment by Deamon5550** [comment]
The logo image in the center of the homepage is about as scaled down as it can be, it has to support transparency which makes it a little larger than it could be otherwise.

I'll look into that css
