### ISSUE TITLE
Players in SWAT are sometimes invisible

### ISSUE THREAD

**Issue by Deamon5550** [TheNexusMC-LLC/Issues#13]
Unverified, needs testing

**Comment by SmellyShelly13** [comment]
I can get a video if you want. I probably have a vid of it already if needed

**Comment by Deamon5550** [comment]
That would be great.

**Comment by SmellyShelly13** [comment]
[Bug](https://www.youtube.com/watch?v=lecLpv6unLQ)

Note: Look right at beginning when I press tab, as you see no one spawned from other team yet they are out of their spawn
