### ISSUE TITLE
Premium Ranks cannot join full games

### ISSUE THREAD

**Issue by Deamon5550** [TheNexusMC-LLC/Issues#35]
Sometimes a premium rank cannot join a game which is full. Reported many times but cannot reproduce so more investigation is needed.

**Comment by andy1ne0** [comment]
According to a few donors - https://thenexusmc.com/forum/topic/28944 - this has happened in SG17 and SG5, if that's of any use.

**Comment by AeroCruz** [comment]
Also being reported by another donor - https://thenexusmc.com/forum/topic/29033

https://www.youtube.com/watch?v=C65dSD-aenU
