### ISSUE TITLE
Factions Loot Chests - Unlimited chests, negative Nexites. 

### ISSUE THREAD

**Issue by andy1ne0** [TheNexusMC-LLC/Issues#37]
I'm not sure if this was already fixed or not - I messaged Kyle about this the other day. If you haven't got enough Nexites to open a lucky loot chest, and you shift+right-click an empty slot in your own inventory while the insufficient Nexites window is open, it will purchase an item from the chest and subtract Nexites from your existing balance. I need both my (TheYellowCreepz)' and Blaze117's (He recreated the bug by accident) Nexite balances reset, along with another player who abused this - I cannot remember off the top of my head - Blaze117 and I have -40 Nexites, and the third player has -280 Nexites, I believe. This issue is only in factions (also tested in hub), I can get video if needed.

**Comment by andy1ne0** [comment]
Slight follow-up, the player who abused this was Relatch.

**Comment by Deamon5550** [comment]
I still cannot reproduce this, are you using any client mods?

**Comment by andy1ne0** [comment]
The only mods I have running are the 5zig Mod and OptiFine. Kyle might have patched it, I'll get video/reproduce it in a moment.

**Comment by andy1ne0** [comment]
Found out that the bug is actually done a different way, which I likely mistook for what I said above. This pertains to the issue where the redstone/emeralds can be removed from a lucky loot chest - if you don't have sufficient Nexites, and you click the glitched emerald block from in your own inventory, it'll deduct Nexites and give you the item. https://www.dropbox.com/s/x2o7g03ou57e30w/OBS_Output1%20%2808%29.mp4?dl=0 - video of the bug. http://i.imgur.com/pXmh5Aw.png My new Nexites balance.

**Comment by Deamon5550** [comment]
Ahh yes I thought that was the cause, there is a fix in the next update coming asap.

**Comment by Deamon5550** [comment]
This has been fixed.

**Comment by andy1ne0** [comment]
Coolio. :D If it's not too much hassle though, would I be able to get my, Blaze117's, and Relatch's Nexites reset? Or who should I message about this?

**Comment by Deamon5550** [comment]
Yeah sure its been done.
