### ISSUE TITLE
Hub inventory doesn't always load in. 

### ISSUE THREAD

**Issue by andy1ne0** [TheNexusMC-LLC/Issues#41]
This is more of a rare bug - it doesn't happen very often, but a month or two ago it was really common. Sometimes, your hub inventory isn't fully loaded in. This just happened to me: http://i.imgur.com/yt3qCvc.png . As seen in this screenshot, the 3rd, 5th, 7th, 8th and 9th slot items are missing. 

(Hub 5, at 6:49pm AEST on the 18th of Feb.)

**Comment by Deamon5550** [comment]
This is one that I am pretty sure has already been fixed (that hub was outdated) but its an odd one where the player profile is empty so we'll have to see if it occurs again.

**Comment by andy1ne0** [comment]
Guessing hub 14 needs to be updated also - just had this bug once more.
