### ISSUE TITLE
Lag on the games page.

### ISSUE THREAD

**Issue by Fabelz** [TheNexusMC-LLC/Issues#52]
Hey, on the website I've noticed the games page loads extremely slow for both I and other players.

I would appreciate this to be fixed, as we could then see the leaderboards easier.

**Comment by andy1ne0** [comment]
See #1

**Comment by Deamon5550** [comment]
Yeah its likely just the images, but there could be other factors.

**Comment by Deamon5550** [comment]
The images on the /games and /games/sg pages have now been scaled down. It should load significantly faster now.

**Comment by Fabelz** [comment]
Yep, the load times are practically instant now.. thanks!
