### ISSUE TITLE
Teaming Limit

### ISSUE THREAD

**Issue by SmellyShelly13** [TheNexusMC-LLC/Issues#60]
This is probably one of the least important things so far but I found it and thought it should be mentioned. On the website when you click "Games" then you click "Survival Games" and look under rules it say "Teams of 3 players max" when now the team limit is 4. Not very important I know but I thought it should be know that it is like that. [Proof (To website](https://thenexusmc.com/games/sg)

**Comment by Deamon5550** [comment]
fixed
