### ISSUE TITLE
Incorrect error message for mutation passes.

### ISSUE THREAD

**Issue by Fabelz** [TheNexusMC-LLC/Issues#67]
Hey! I was in a USG match recently, https://thenexusmc.com/game/2914664 (To be precise) and I noticed that when I went to hover over to mutate it said that there were no mutations in ranked matches, instead of undead matches.
![2016-03-07_02 36 24](https://cloud.githubusercontent.com/assets/15955937/13555190/c6461456-e40d-11e5-8a98-1feb198ef711.png)

**Comment by Deamon5550** [comment]
Fixed
