### ISSUE TITLE
Sentinel Strike - Kills not 'Registering' 

### ISSUE THREAD

**Issue by Mystycql** [TheNexusMC-LLC/Issues#72]
This gamemode is amazing, however Ive already found a little issue.
When you kill someone, you don't  receive credits for it. 
When you kill assist, you do. 

Kills are also not registering on the /stats 
[http://i.imgur.com/kZFgAo4.png](url)
As seen in the above image, I have 2 deaths however no kills are recorded, even though I killed around 4-5 players.

**Comment by Deamon5550** [comment]
This was fixed
