### ISSUE TITLE
Sentinel Strike - Lobby Time

### ISSUE THREAD

**Issue by Mystycql** [TheNexusMC-LLC/Issues#73]
Problem: From what I've seen so far, the game countdown in the lobby only starts when the game is full (16/16 players), although this makes perfect sense, I've found myself waiting in a lobby for over 10 minutes waiting for a game to start, with people constantly leaving when there is only a few seconds until the game begins. 

Suggestion: Maybe make it so when the timer hits 20 seconds, even if someone leaves, the game timer will continue to countdown.
Or alternatively, 
Make the minimum player limit 12

**Comment by Deamon5550** [comment]
Minimum is 8
