### ISSUE TITLE
Website pages that need updating

### ISSUE THREAD

**Issue by Deamon5550** [TheNexusMC-LLC/Issues#82]
Many pages on the site have fallen very out of date:

- [ ] [/games](https://thenexusmc.com/games/) - Missing many new games
- [x] [/games/sg](https://thenexusmc.com/games/sg) - Missing recent map additions

Feel free to identify additiona pages in need of updating

**Comment by SmellyShelly13** [comment]
Other than ones known (SW leaderboards, new maps ect.). I think some are moving SW and CTF out of "Newest Games" and putting SS there instead. Also adding SnD (leaderboards and just info and rules), LLW (leaderboards and info/rules), MR (leaderboards and info/rules) and SS (leaderboards and info/rules). Maybe also putting these stats on players profiles. Another thing is maybe if you click "Survival Games" it would come with another menu says "Solo SG", "Undead SG" and "Normal SG" and it would have the rules under each game mode. Also, when clicking "Factions" it takes you no where. Maybe make it so it it will give a description of it and maybe link to the shop with faction items. All the new SW maps. Last, maybe on website for SG it could have the "Most lethal" and "Most chest looted"  not just the highest score.
